
package com.ys.webserverclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DIYWebServerService", targetNamespace = "http://diywebserver.ys.com/", wsdlLocation = "http://127.0.0.1:12345/meserver?wsdl")
public class DIYWebServerService
    extends Service
{

    private final static URL DIYWEBSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DIYWEBSERVERSERVICE_EXCEPTION;
    private final static QName DIYWEBSERVERSERVICE_QNAME = new QName("http://diywebserver.ys.com/", "DIYWebServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12345/meserver?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIYWEBSERVERSERVICE_WSDL_LOCATION = url;
        DIYWEBSERVERSERVICE_EXCEPTION = e;
    }

    public DIYWebServerService() {
        super(__getWsdlLocation(), DIYWEBSERVERSERVICE_QNAME);
    }

    public DIYWebServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIYWEBSERVERSERVICE_QNAME, features);
    }

    public DIYWebServerService(URL wsdlLocation) {
        super(wsdlLocation, DIYWEBSERVERSERVICE_QNAME);
    }

    public DIYWebServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIYWEBSERVERSERVICE_QNAME, features);
    }

    public DIYWebServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DIYWebServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DIYWebServer
     */
    @WebEndpoint(name = "DIYWebServerPort")
    public DIYWebServer getDIYWebServerPort() {
        return super.getPort(new QName("http://diywebserver.ys.com/", "DIYWebServerPort"), DIYWebServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DIYWebServer
     */
    @WebEndpoint(name = "DIYWebServerPort")
    public DIYWebServer getDIYWebServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://diywebserver.ys.com/", "DIYWebServerPort"), DIYWebServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIYWEBSERVERSERVICE_EXCEPTION!= null) {
            throw DIYWEBSERVERSERVICE_EXCEPTION;
        }
        return DIYWEBSERVERSERVICE_WSDL_LOCATION;
    }

}
