
package com.ys.webserverclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DIYWebServer", targetNamespace = "http://diywebserver.ys.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DIYWebServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryTheWeather", targetNamespace = "http://diywebserver.ys.com/", className = "com.ys.webserverclient.QueryTheWeather")
    @ResponseWrapper(localName = "queryTheWeatherResponse", targetNamespace = "http://diywebserver.ys.com/", className = "com.ys.webserverclient.QueryTheWeatherResponse")
    @Action(input = "http://diywebserver.ys.com/DIYWebServer/queryTheWeatherRequest", output = "http://diywebserver.ys.com/DIYWebServer/queryTheWeatherResponse")
    public String queryTheWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
